### ISSUE TITLE
Text Extraction Filtering

### ISSUE THREAD

**Issue by armintalaie** [ubclaunchpad/Essentially#49]
currently, the text extraction picks up lots of irrelevant text and HTML tags. 

we need better removing of tags. Additionally, we can add as many rules as possible to avoid extracting buttons or ads (e.g. if the id of element is "ad")

potentially we can use some post-processing library in the React app. for instance, the text is extracted and passed to our extension. we will then run it through a library on our react side to weed out other extra stuff. this seems more feasible than implementing everything manually.

_@sauravbanna initially did the extraction. refer to him if you have any questions_

## Acceptance criteria
- not pick up HTML tag
- not pick up button, nav and irrelevant section
- summary API shouldn't be passed anything but the main text

**Comment by Michaeltaoma** [comment]
Can anyone review if this pr #74 resolves this issue? @ubclaunchpad/tldr , If so, we can close it.

**Comment by armintalaie** [comment]
> Can anyone review if this pr #74 resolves this issue already @ubclaunchpad/tldr？If so, we can close this issue. What I did in that pr is to extract only the text instead of the HTML content when processing a webpage.

i think some it got covered by your other PR but running the summary still produces weird text. (depends on the article). only piece missing is to see if we can tell what is actually the website article and not a comment on the page or something like that

**Comment by Michaeltaoma** [comment]
> > Can anyone review if this pr #74 resolves this issue already @ubclaunchpad/tldr？If so, we can close this issue. What I did in that pr is to extract only the text instead of the HTML content when processing a webpage.
> 
> i think some it got covered by your other PR but running the summary still produces weird text. (depends on the article). only piece missing is to see if we can tell what is actually the website article and not a comment on the page or something like that

Got u, I will take a look later.

**Comment by Michaeltaoma** [comment]
Hi @armintalaie , I looked at the issue and couldn't find a perfect solution. We can

1. retrieve the article based on HTML query selection, but since different websites use different naming conventions, enforcing this will cause an increase of false negative
2. call/build our own filtering API with ml, but this overlaps with the summarization since this API would perform "filtering out information that is not part of the article." Our summarization API (if trained well) should already be doing the job.

That said, I think the filtering part should be left with summarization API because that's what summarization is meant to be doing.
